services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mable
      POSTGRES_PASSWORD: mable
      POSTGRES_DB: mable_assessment_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: